name: Docker Multi-Architecture Build

on:
  push: {}

jobs:
  build-docker:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - name: install buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
          qemu-version: latest
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: cache docker cache
        uses: actions/cache@v1
        with: 
          path: ${{ github.workspace }}/cache
          key: ${{ runner.os }}-docker-${{ hashfiles('cache/**') }}
          restore-keys: |
            ${{ runner.os }}-docker-
      - name: build docker image
        run: >
          docker buildx build .
          --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
          --cache-from "type=local,src=$GITHUB_WORKSPACE/cache"
          --cache-to "type=local,dest=$GITHUB_WORKSPACE/cache"
          --output "type=image, name=1337kavin/yotter:latest,push=true"
