name: Docker Multi-Architecture Build

on:
  push:
    paths-ignore:
    - '**.md'

jobs:
  build-docker:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: cache docker cache
        uses: actions/cache@v1
        with: 
          path: ${{ github.workspace }}/cache
          key: ${{ runner.os }}-docker-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-docker-${{ hashFiles('**/requirements.txt') }}
      - name: build docker image
        run: >
          docker buildx build .
          --platform linux/amd64,linux/arm64
          --cache-from "type=local,src=$GITHUB_WORKSPACE/cache"
          --cache-to "type=local,dest=$GITHUB_WORKSPACE/cache"
          --output "type=image, name=1337kavin/yotter:latest,push=true"
